### ISSUE TITLE
Segfault on macOS in Func error handling

### ISSUE THREAD

**Issue by jbourassa** [bytecodealliance/wasmtime-rb#156]
Func error handling can segfault on macOS. Reproduction cases are in the [`macos-segfault` branch](https://github.com/bytecodealliance/wasmtime-rb/compare/macos-segfault).

[Minmal repro script](https://github.com/bytecodealliance/wasmtime-rb/blob/a7af5dbc72ee2d8d3238d6be6e3f9297d9e7be86/examples/crash.rb): 

```ruby
require "wasmtime"

GC.stress = true
store = Wasmtime::Store.new(Wasmtime::Engine.new, Object.new)
func = Wasmtime::Func.new(store, [], [:i32, :i32]) { [1, nil] }

1_000.times do
  func.call
rescue Wasmtime::ResultError
end
```

To repro, checkout the `macos-segfault` branch, compile the gem with `rake compile:release`, and run `ruby -Ilib examples/crash.rb` or `rake spec`.

Can't reproduce on Linux. Valgrind doesn't see an issue either:

```
$ valgrind -- ruby -Ilib examples/crash.rb
==106779== Memcheck, a memory error detector
==106779== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==106779== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==106779== Command: /home/jbourassa.linux/.rbenv/shims/ruby -Ilib examples/crash.rb
==106779==
Using wasmtime-rb 6.0.1: /home/jbourassa.linux/wasmtime-rb/lib/wasmtime/wasmtime_rb.so
```
Changing the memory allocator (`MallocNanoZone` env var) gives different crash reports when running the test. The minimal repro case doesn't fail with `MallocNanoZone=0` (`MallocNanoZone=0 ruby -Ilib examples/crash.rb`) no idea why.

**Comment by ianks** [comment]
Seems this issue doesn't exist on 5.0

```sh
❯ ruby -Ilib examples/crash.rb
Using wasmtime-rb 5.0.0: /Users/ianks/.gem/ruby/3.2.1/gems/wasmtime-5.0.0-arm64-darwin/lib/wasmtime/3.2/wasmtime_rb.bundle
Done!
❯ ruby --version
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]
❯ uname -a
Darwin ianks-shopify.lan 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
```

**Comment by ianks** [comment]
I think I've tracked this down to an LTO issue in `release` mode. This diff makes things work:

```diff
diff --git i/Cargo.toml w/Cargo.toml
index 0103f51..6dcb193 100644
--- i/Cargo.toml
+++ w/Cargo.toml
@@ -4,6 +4,6 @@ members = ["ext"]
 exclude = ["examples/rust-crate"]
 
 [profile.release]
-codegen-units = 1 # more llvm optimizations
+codegen-units = 1 # better codegen
 debug = 2 # make perfomance engineers happy
 lto = "thin" # cross-crate inlining
```

When I set a breakpoint in `malloc_error_break`, it seems to me like a drop destructor is being called will with a null pointer, of size 40 bytes. So it seems like a ruby object is being dropped.

Browsing through the code, I noticed a[ suspicious use of `Params::to_vec`](https://github.com/bytecodealliance/wasmtime-rb/blob/e07410945d4c8722490103a0e47f4624309870f0/ext/src/ruby_api/func.rs#L179) when invoking a function. Usually that's fine, but the compiler can optimize those values off the stack, allowing Ruby to GC them.

Instead of using a `Vec<RValue>` then derefenceing (`func.call(context, &params, &mut results)`), we should try using a fixed size arg buffer which overflows into an RArray:

```rust
/// The backing storage for an `ArgBuf`, either a stack allocated array or a
/// heap allocated array depending on the size.
#[derive(Debug)]
enum ArgBuf {
    Stack([Value; ArgBuf::MAX_SIZE]),
    Heap(RArray),
}

impl ArgBuf {
  // push to fixed size stack buffer, if we have too many args convert to an RArray
}
```

**Comment by jbourassa** [comment]
Mat put his finger on the actual [issue here](https://github.com/bytecodealliance/wasmtime-rb/pull/158#issuecomment-1483986273):
> Then, later, [the `caller` variable, which is a reference to the wrapped data, is used](https://github.com/bytecodealliance/wasmtime-rb/blob/e07410945d4c8722490103a0e47f4624309870f0/ext/src/ruby_api/func.rs#L270). The `caller.expire()` sets an `Option` to `None`, freeing the data it contained. My guess it this has already been freed when Ruby dropped `wrapped_caller`, then after a couple of double frees the allocator's free list is corrupted.

After learning about LLVM's Sanitizer and running it, I could validate that theory ([full report](https://gist.github.com/jbourassa/82f3a89c83465ae33c7875338c923200)). The memory was freed by the GC:

```
0x000106e5af30 is located 0 bytes inside of 16-byte region [0x000106e5af30,0x000106e5af40)
freed by thread T0 here:
    #0 0x10329ace4 in wrap_free+0x8c (librustc-nightly_rt.asan.dylib:arm64+0x3ece4) (BuildId: 31bdcb1179dd3203aa5361ad5e96177032000000200000000100000000000b00)
    #1 0x112a02ba4 in __rust_try+0x1c (wasmtime_rb.bundle:arm64+0xe76ba4) (BuildId: 29e7e1e1b9273419b16b31f1efe2aae932000000200000000100000000000d00)
    #2 0x11299e784 in magnus::typed_data::DataTypeFunctions::extern_free::h204833853071aa81 typed_data.rs:130
    #3 0x104544450 in obj_free+0x8a0 (libruby.3.2.dylib:arm64+0xc0450) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #4 0x104543aac in gc_sweep_page+0x270 (libruby.3.2.dylib:arm64+0xbfaac) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #5 0x104542250 in gc_sweep_step+0x130 (libruby.3.2.dylib:arm64+0xbe250) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #6 0x104541c00 in gc_sweep+0xa40 (libruby.3.2.dylib:arm64+0xbdc00) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #7 0x104547040 in gc_start+0xd98 (libruby.3.2.dylib:arm64+0xc3040) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #8 0x10453a748 in objspace_xmalloc0+0xb8 (libruby.3.2.dylib:arm64+0xb6748) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #9 0x1046cf9a0 in callable_method_entry_or_negative+0x248 (libruby.3.2.dylib:arm64+0x24b9a0) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #10 0x1046d4580 in rb_check_funcall_default_kw+0x178 (libruby.3.2.dylib:arm64+0x250580) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #11 0x1045bd22c in convert_type_with_id+0x38 (libruby.3.2.dylib:arm64+0x13922c) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #12 0x1045bd7b4 in rb_to_int+0x48 (libruby.3.2.dylib:arm64+0x1397b4) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #13 0x104522d0c in rb_protect+0x160 (libruby.3.2.dylib:arm64+0x9ed0c) (BuildId: abc4c43c0bf83de58701765c9b2dec8e32000000200000000100000000000d00)
    #14 0x112044bbc in _$LT$magnus..integer..Integer$u20$as$u20$magnus..try_convert..TryConvert$GT$::try_convert::hc2d0c9bda7181f5f integer.rs:415
    #15 0x11204ec58 in _$LT$i32$u20$as$u20$magnus..try_convert..TryConvert$GT$::try_convert::hdfd15b80ab65208a try_convert.rs:81
    #16 0x1129d41e0 in _$LT$magnus..value..Value$u20$as$u20$wasmtime_rb..ruby_api..convert..ToWasmVal$GT$::to_wasm_val::he113da9357e12752 convert.rs:68
    #17 0x1129dc07c in wasmtime_rb::ruby_api::func::make_func_closure::_$u7b$$u7b$closure$u7d$$u7d$::hc435f6e5fd9cf7d8 func.rs:230
    #18 0x1129c500c in wasmtime::func::Func::invoke::hc54fcea15d9124cb func.rs:1125
    #19 0x11294fb10 in std::panicking::try::do_call::hf6708b0126bf6553 panicking.rs:487
    #20 0x112a02ba4 in __rust_try+0x1c (wasmtime_rb.bundle:arm64+0xe76ba4) (BuildId: 29e7e1e1b9273419b16b31f1efe2aae932000000200000000100000000000d00)
    #21 0x1129c4598 in wasmtime::trampoline::func::stub_fn::h72c605e476de8712 func.rs:39
    #22 0x1041f8090  (<unknown module>)
    #23 0xa2d0001041f8020  (<unknown module>)
    #24 0x914f800112d0177c  (<unknown module>)
    #25 0x1129c66d0 in wasmtime::func::Func::call_impl::h11763b1bee0d92fc func.rs:1053
```

The only logical explanation I see for that the VALUE does not stay on the stack.

Potential fixes: use `Obj.get()` right before expiring the caller. It no longer crashes when doing so, and AddressSanitizer does not catch anything.
